package org.example;

import java.util.ArrayList;
import java.util.List;

public class Data {

    public static List<ISO8583> iso8583Element(){
        //DATA ISO8583 ELEMENTS
        List<ISO8583> isoElements = new ArrayList<>();
        isoElements.add(new ISO8583("bit_0", "mti"));
        isoElements.add(new ISO8583("bit_2", "Card Number"));
        isoElements.add(new ISO8583("bit_3", "Processing Code"));
        isoElements.add(new ISO8583("bit_4", "Amount"));
        isoElements.add(new ISO8583("bit_5", "Amount, Reconciliation"));
        isoElements.add(new ISO8583("bit_6", "Amount, Cardholder Billing"));
        isoElements.add(new ISO8583("bit_7", "Transmission Date Time"));
        isoElements.add(new ISO8583("bit_8", "Amount, Cardholder Billing Fee"));
        isoElements.add(new ISO8583("bit_9", "Conversion Rate, Reconciliation"));
        isoElements.add(new ISO8583("bit_10", "Conversion Rate, Cardholder Billing"));
        isoElements.add(new ISO8583("bit_11", "System Trace Audit Number"));
        isoElements.add(new ISO8583("bit_12", "Local Time"));
        isoElements.add(new ISO8583("bit_13", "Local Date"));
        isoElements.add(new ISO8583("bit_14", "Date, Expiration"));
        isoElements.add(new ISO8583("bit_15", "Date, Settlement"));
        isoElements.add(new ISO8583("bit_16", "Date, Conversion"));
        isoElements.add(new ISO8583("bit_17", "Capture Date"));
        isoElements.add(new ISO8583("bit_18", "Merchant Type"));
        isoElements.add(new ISO8583("bit_19", "Acquiring Institution Country Code"));
        isoElements.add(new ISO8583("bit_20", "Primary Account Number Extended, Country Code"));
        isoElements.add(new ISO8583("bit_21", "Forwarding Institution Extended, Country Code"));
        isoElements.add(new ISO8583("bit_22", "Pos Entry Mode"));
        isoElements.add(new ISO8583("bit_23", "Primary Account Number (PAN) Sequence Number"));
        isoElements.add(new ISO8583("bit_24", "Network International Identifier (NII)"));
        isoElements.add(new ISO8583("bit_25", "Point of Service Condition Code"));
        isoElements.add(new ISO8583("bit_26", "Point of Service PIN Capture Code"));
        isoElements.add(new ISO8583("bit_27", "Authorization Identification Response Length"));
        isoElements.add(new ISO8583("bit_28", "Amount, Transaction Fee"));
        isoElements.add(new ISO8583("bit_29", "Amount, Reconciliation Fee"));
        isoElements.add(new ISO8583("bit_30", "Amount, Transaction Processing Fee"));
        isoElements.add(new ISO8583("bit_31", "Amount, Reconciliation Processing Fee"));
        isoElements.add(new ISO8583("bit_32", "Acquirer ID"));
        isoElements.add(new ISO8583("bit_33", "Forwarding Institution ID Code"));
        isoElements.add(new ISO8583("bit_34", "Primary Account Number (PAN) Extended"));
        isoElements.add(new ISO8583("bit_35", "Track 2 Data"));
        isoElements.add(new ISO8583("bit_36", "Track 3 Data"));
        isoElements.add(new ISO8583("bit_37", "Retrieval Reference Number"));
        isoElements.add(new ISO8583("bit_38", "Authorization Identification Response"));
        isoElements.add(new ISO8583("bit_39", "Response Code"));
        isoElements.add(new ISO8583("bit_40", "Service Restriction Code"));
        isoElements.add(new ISO8583("bit_41", "Terminal ID"));
        isoElements.add(new ISO8583("bit_42", "Card Acceptor ID Code"));
        isoElements.add(new ISO8583("bit_43", "Terminal Info"));
        isoElements.add(new ISO8583("bit_44", "Additional Response Data"));
        isoElements.add(new ISO8583("bit_45", "Track 1 Data"));
        isoElements.add(new ISO8583("bit_46", "Additional Data - ISO"));
        isoElements.add(new ISO8583("bit_47", "Additional Data - National"));
        isoElements.add(new ISO8583("bit_48", "Additional Data - Private"));
        isoElements.add(new ISO8583("bit_49", "Currency Code"));
        isoElements.add(new ISO8583("bit_50", "Currency Code, Reconciliation"));
        isoElements.add(new ISO8583("bit_51", "Currency Code, Cardholder Billing"));
        isoElements.add(new ISO8583("bit_52", "Pin Data"));
        isoElements.add(new ISO8583("bit_53", "Security-Related Control Information"));
        isoElements.add(new ISO8583("bit_54", "Additional Amounts"));
        isoElements.add(new ISO8583("bit_55", "ICC Data"));
        isoElements.add(new ISO8583("bit_56", "Reserved ISO"));
        isoElements.add(new ISO8583("bit_57", "Reserved National"));
        isoElements.add(new ISO8583("bit_58", "Reserved National"));
        isoElements.add(new ISO8583("bit_59", "Reserved National"));
        isoElements.add(new ISO8583("bit_60", "Reserved National"));
        isoElements.add(new ISO8583("bit_61", "Reserved Private"));
        isoElements.add(new ISO8583("bit_62", "Reserved Private"));
        isoElements.add(new ISO8583("bit_63", "Reserved Private"));
        isoElements.add(new ISO8583("bit_64", "Message Authentication Code (MAC)"));
        isoElements.add(new ISO8583("bit_65", "Reserved ISO"));
        isoElements.add(new ISO8583("bit_66", "Original Data Elements"));
        isoElements.add(new ISO8583("bit_67", "Extended Payment Code"));
        isoElements.add(new ISO8583("bit_68", "Receiving Institution Country Code"));
        isoElements.add(new ISO8583("bit_69", "Settlement Institution Country Code"));
        isoElements.add(new ISO8583("bit_70", "Network Management Information Code"));
        isoElements.add(new ISO8583("bit_71", "Message Number"));
        isoElements.add(new ISO8583("bit_72", "Message Number, Last"));
        isoElements.add(new ISO8583("bit_73", "Date, Action"));
        isoElements.add(new ISO8583("bit_74", "Number of Credits"));
        isoElements.add(new ISO8583("bit_75", "Number of Credits, Reversal"));
        isoElements.add(new ISO8583("bit_76", "Number of Debits"));
        isoElements.add(new ISO8583("bit_77", "Number of Debits, Reversal"));
        isoElements.add(new ISO8583("bit_78", "Number of Transfers"));
        isoElements.add(new ISO8583("bit_79", "Number of Transfers, Reversal"));
        isoElements.add(new ISO8583("bit_80", "Number of Enquiries"));
        isoElements.add(new ISO8583("bit_81", "Number of Authorizations"));
        isoElements.add(new ISO8583("bit_82", "Amount, Credits, Processing Fee"));
        isoElements.add(new ISO8583("bit_83", "Admin Fee"));
        isoElements.add(new ISO8583("bit_84", "Amount, Debits, Processing Fee"));
        isoElements.add(new ISO8583("bit_85", "Amount, Debits, Transaction Fee"));
        isoElements.add(new ISO8583("bit_86", "Amount, Credits"));
        isoElements.add(new ISO8583("bit_87", "Amount, Credits, Reversal"));
        isoElements.add(new ISO8583("bit_88", "Amount, Debits"));
        isoElements.add(new ISO8583("bit_89", "Amount, Debits, Reversal"));
        isoElements.add(new ISO8583("bit_90", "Original Data Elements"));
        isoElements.add(new ISO8583("bit_91", "File Update Code"));
        isoElements.add(new ISO8583("bit_92", "File Security Code"));
        isoElements.add(new ISO8583("bit_93", "Response Indicator"));
        isoElements.add(new ISO8583("bit_94", "Service Indicator"));
        isoElements.add(new ISO8583("bit_95", "Replacement Amount"));
        isoElements.add(new ISO8583("bit_96", "Message Security Code"));
        isoElements.add(new ISO8583("bit_97", "Amount, Net Settlement"));
        isoElements.add(new ISO8583("bit_98", "Payee"));
        isoElements.add(new ISO8583("bit_99", "Settlement Institution ID Code"));
        isoElements.add(new ISO8583("bit_100", "Issuer ID"));
        isoElements.add(new ISO8583("bit_101", "File Name"));
        isoElements.add(new ISO8583("bit_102", "Debit Account No"));
        isoElements.add(new ISO8583("bit_103", "Credit Account No"));
        isoElements.add(new ISO8583("bit_104", "Transaction Description"));
        isoElements.add(new ISO8583("bit_105", "GL Account"));
        isoElements.add(new ISO8583("bit_106", "Reserved for ISO use"));
        isoElements.add(new ISO8583("bit_107", "Reserved for ISO use"));
        isoElements.add(new ISO8583("bit_108", "Reserved for ISO use"));
        isoElements.add(new ISO8583("bit_109", "Reserved for ISO use"));
        isoElements.add(new ISO8583("bit_110", "Reserved for ISO use"));
        isoElements.add(new ISO8583("bit_111", "Reserved for ISO use"));
        isoElements.add(new ISO8583("bit_112", "Reserved for National use"));
        isoElements.add(new ISO8583("bit_113", "Reserved for National use"));
        isoElements.add(new ISO8583("bit_114", "Reserved for National use"));
        isoElements.add(new ISO8583("bit_115", "Reserved for National use"));
        isoElements.add(new ISO8583("bit_116", "Reserved for National use"));
        isoElements.add(new ISO8583("bit_117", "Reserved for National use"));
        isoElements.add(new ISO8583("bit_118", "Reserved for National use"));
        isoElements.add(new ISO8583("bit_119", "Reserved for National use"));
        isoElements.add(new ISO8583("bit_120", "Reserved for Private use"));
        isoElements.add(new ISO8583("bit_121", "Reserved for Private use"));
        isoElements.add(new ISO8583("bit_122", "Reserved for Private use"));
        isoElements.add(new ISO8583("bit_123", "Reserved for Private use"));
        isoElements.add(new ISO8583("bit_124", "Reserved for Private use"));
        isoElements.add(new ISO8583("bit_125", "Reserved for Private use"));
        isoElements.add(new ISO8583("bit_126", "Additional Data"));
        isoElements.add(new ISO8583("bit_127", "Reserved for Private use"));
        isoElements.add(new ISO8583("bit_128", "Message Authentication Code (MAC)"));
        return isoElements;
    }
}
